# Generated by Django 2.2.5 on 2019-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20190924_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfilm',
            name='film',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
