# Generated by Django 2.2.5 on 2019-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
