# Generated by Django 2.2.5 on 2019-11-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
