# Generated by Django 2.2.5 on 2019-11-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
